export const INCREASE_INGREDIENT = 'INCREASE_INGREDIENT';
export const DECREASE_INGREDIENT = 'DECREASE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_ERROR = 'SET_INGREDIENTS_ERROR';

export const BURGER_ORDER_SUCCESSFUL = 'BURGER_ORDER_SUCCESSFUL';
export const BURGER_ORDER_FAILED = 'BURGER_ORDER_FAILED';
export const SET_BURGER_ORDER_SUBMITTING = 'SET_BURGER_ORDER_SUBMITTING';

export const SET_ORDERS = 'SET_ORDERS';
export const SET_ORDERS_LOADING = 'SET_ORDERS_LOADING';
export const SET_ORDERS_ERROR = 'SET_ORDERS_ERROR';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
